version: '3'
services:
  web:
    build: .
    image: kamontia/cheerhawks
    tty: true
    ports:
      - "9000:9000"
    command: sbt run
    links:
      - db
  db:
    image: mysql:5.7.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cheerhawks
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db-data:/var/lib/mysql
      - ./mysql:/etc/mysql/conf.d
volumes:
  db-data:
    driver: local
