version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ssh -t -o StrictHostKeyChecking=no share.kamo.club "cd /usr/local/cheerHawks/ && sudo git pull"
            fi
